# Named Tunnel setup for Map v12 (Windows PowerShell)
#
# Purpose:
# - Create a named Cloudflare Tunnel
# - Route DOMAIN -> your local server (http://localhost:8000)
# - Generate %USERPROFILE%\.cloudflared\config.yml
#
# Usage:
#   Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
#   ./named_tunnel_setup.ps1 -TunnelName "mapv12" -Domain "madcommandcentre.org"

param(
  [Parameter(Mandatory=$false)][string]$TunnelName = "mapv12",
  [Parameter(Mandatory=$false)][string]$Domain = "madcommandcentre.org",
  [Parameter(Mandatory=$false)][string]$Service = "http://localhost:8000"
)

$ErrorActionPreference = "Stop"

function Find-Cloudflared {
  $candidates = @(
    "C:\\Program Files (x86)\\cloudflared\\cloudflared.exe",
    "C:\\Program Files\\cloudflared\\cloudflared.exe"
  )
  foreach($p in $candidates){ if(Test-Path $p){ return $p } }
  $cmd = Get-Command cloudflared -ErrorAction SilentlyContinue
  if($cmd){ return $cmd.Source }
  throw "cloudflared not found. Install from Cloudflare and ensure it's in PATH."
}

$cloudflared = Find-Cloudflared
Write-Host "Using cloudflared: $cloudflared"

Write-Host "1) Login (opens browser)..."
& $cloudflared tunnel login

Write-Host "2) Create tunnel: $TunnelName"
$createOut = & $cloudflared tunnel create $TunnelName 2>&1
if($LASTEXITCODE -ne 0){ throw "tunnel create failed: $createOut" }

# Extract UUID (tunnel id) from output
$tunnelId = $null
if($createOut -match "([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12})"){ $tunnelId = $Matches[1] }
if(-not $tunnelId){
  Write-Host $createOut
  throw "Cannot parse tunnel id from cloudflared output."
}
Write-Host "Tunnel ID: $tunnelId"

# Route DNS
Write-Host "3) Route DNS: $Domain -> $TunnelName"
& $cloudflared tunnel route dns $TunnelName $Domain
& $cloudflared tunnel route dns $TunnelName ("www." + $Domain)

# Write config.yml
$cfDir = Join-Path $env:USERPROFILE ".cloudflared"
if(-not (Test-Path $cfDir)){ New-Item -ItemType Directory -Path $cfDir | Out-Null }

$configPath = Join-Path $cfDir "config.yml"
$credPath = Join-Path $cfDir ("$tunnelId.json")

$cfg = @"
# Auto-generated by named_tunnel_setup.ps1

tunnel: $tunnelId
credentials-file: $credPath

ingress:
  - hostname: $Domain
    service: $Service
  - hostname: www.$Domain
    service: $Service
  - service: http_status:404
"@

Set-Content -Path $configPath -Value $cfg -Encoding UTF8
Write-Host "Written: $configPath"

Write-Host "4) Run tunnel:"
Write-Host "   cloudflared tunnel run $TunnelName"

Write-Host "5) Update your server .env:"
Write-Host "   BOOTSTRAP_PREFERRED_BASE_URL=https://$Domain"
Write-Host "   REALTIME_ALLOWED_ORIGINS=https://$Domain"
